rvm:
  - 2.6

env: >-
  TESTMETRICS_PROJECT_KEY="H8ina9VG4PqMHONU9Oi09A"

before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler

install: "bundle install --jobs 8"
script: "bundle exec rake"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

sudo: false
cache: bundler
